name: mm_notes
description: A simple flutter application showcasing the real life usage of Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite:
  path_provider:
  flutter_staggered_grid_view:
  intl:
  animations: ^2.0.2
  get:
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'ProductSans'
      fonts:
        - asset: assets/ProductSans-Bold.ttf
        - asset: assets/ProductSans-Bold-Italic.ttf
        - asset: assets/ProductSans-Italic.ttf
        - asset: assets/ProductSans-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
